# 감정 분류 모델1

## 데이터 불러오기 - 감성 대화 말뭉치

In [12]:
# import json

# # 말웅치 json 읽기
# with open('.\데이터셋\감성대화\Training_221115_add\라벨링데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.json', 'r', encoding='utf-8') as f:
#     data = json.load(f)

# # 첫 번째 데이터의 대화 내용 출력 예시
# print(data[0]['talk']['content'])

In [13]:
# data
# # 구조 : [ {'profile' : {딕셔너리 여러개}  , 'id' : {딕셔너리 여러개} } ]

In [33]:
import pandas as pd

# 말뭉치 training 데이터
data_url = ".\데이터셋\감성대화\Training_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.xlsx"
# data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화말뭉치(최종데이터)_Training.xlsx"
df = pd.read_excel(data_url)
df.head(5)

# '''print(df["감정_대분류"].value_counts())
# print("\nunique 값:", df["감정_대분류"].unique())'''

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,일은 왜 해도 해도 끝이 없을까? 화가 난다.,많이 힘드시겠어요. 주위에 의논할 상대가 있나요?,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.,혼자 해결하기로 했군요. 혼자서 해결하기 힘들면 주위에 의논할 사람을 찾아보세요.,NaN,NaN
1,2,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,급여가 줄어 속상하시겠어요. 월급이 줄어든 것을 어떻게 보완하실 건가요?,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.,월급이 줄어든 만큼 소비를 줄일 계획이군요.,NaN,NaN
2,3,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,회사 동료 때문에 스트레스를 많이 받는 것 같아요. 문제 해결을 위해 어떤 노력을 ...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...,스트레스받지 않기 위해선 인간관계에 있어 약간의 거리를 두는 게 좋겠군요.,NaN,NaN
3,4,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,관련 없는 심부름을 모두 하게 되어서 노여우시군요. 어떤 것이 상황을 나아질 수 있...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.,직장 사람들과 이야기를 해 보겠다고 결심하셨군요.,NaN,NaN
4,5,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,무시하는 것 같은 태도에 화가 나셨군요. 상대방의 어떤 행동이 그런 감정을 유발하는...,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!,항상 먼저 인사하게 되어 화가 나셨군요. 어떻게 하면 신입사원에게 화났음을 표현할 ...,NaN,NaN

In [34]:
import pandas as pd

# 말뭉치 validation 데이터
data_url = ".\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx"
# data_url = r"C:\Users\asia\Desktop\ㅛㅔ미2\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx"
df = pd.read_excel(data_url)
df.head(5)

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번 프로젝트에서 발표를 하는데 내가 실수하는 바람에 우리 팀이 감점을 받았어. 너...,실수하시다니 정말 미안한 마음이 크겠어요.,내 능력이 부족한 거 같은데 그만 다녀야 될거같아.,능력을 올리려면 어떤 방법이 있을까요?,퇴근 후 여가에 회사 일을 더 열심히 해서 피해가 가지 않도록 해야겠어.,꼭 좋은 결과 있길 바라요.
1,2,청년,남성,"진로,취업,직장",해당없음,불안,두려운,회사에서 중요한 프로젝트를 혼자 하게 됐는데 솔직히 두렵고 무서워.,큰 프로젝트를 혼자 하셔서 고민이 많겠네요.,나에게 너무 크게 느껴지는 중요한 프로젝트라 버거운 느낌이 들어.,프로젝트를 잘하시기 위해서 어떤 걸 할 수 있나요?,동료 직원에게 도움을 요청해서 같이 해결해야겠어.,동료 직원에게 도움을 요청하기로 하셨군요.
2,3,청년,남성,"진로,취업,직장",해당없음,불안,두려운,상사가 너무 무섭게 생겨서 친해지는 게 너무 두려워.,직장 상사가 무섭게 생기셔서 친해지는 게 어렵군요.,무섭게 생겼는데도 업무를 보려면 친해져야 할 것 같단말이야.,상사분과 친해질 수 있는 방법은 무엇이 있을까요?,먼저 다가가서 말을 걸어볼게.,직장 상사와 친해지시면 좋겠네요.
3,4,청년,남성,"진로,취업,직장",해당없음,불안,두려운,이번에 힘들게 들어간 첫 직장이거든. 첫 직장이라서 그런지 너무 긴장된다.,첫 직장이라서 정말 떨리시고 긴장되실 것 같아요.,첫 직장이어서 잘 적응을 할 수 있을지 모르겠어.,잘 적응 하시려면 무엇을 할 수 있을까요?,직장 동료와 상사들이랑 친하게 지내야겠어.,직장에 잘 적응하시길 바라요.
4,5,청년,남성,"진로,취업,직장",해당없음,불안,두려운,직장에서 동료들이랑 관계가 안 좋아질까 봐 걱정돼.,직장 사람들 관계에 대해서 고민이시군요.,내가 낯가림이 심해서 친해질 수 있을지 모르겠어.,직장 사람들과 친해지려면 무슨 방법이 있을까요?,서로 같은 취미를 공유하고 얘기를 나누다 보면 친해질 수 있을 거 같아.,직장 사람들과 좋은 관계를 가지시길 응원해요.

## 데이터 합치기

In [35]:
import pandas as pd
import numpy as np

# 데이터 로드


# 말뭉치 training 데이터
fin_t=pd.read_excel(".\데이터셋\감성대화\Training_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Training\감성대화말뭉치(최종데이터)_Training.xlsx", engine='openpyxl')

# 말뭉치 validation 데이터
fin_v=pd.read_excel(".\데이터셋\감성대화\Validation_221115_add\원천데이터\감성대화말뭉치(최종데이터)_Validation.xlsx", engine='openpyxl')


# 빈칸은 nan으로 결측치 처리
fin_t=fin_t.fillna("")
fin_v=fin_v.fillna("")

# 사람문장 1,2,3을 한 컬럼으로 합치기
fin_t["사람문장"]=fin_t["사람문장1"].astype(str)+fin_t["사람문장2"].astype(str)+fin_t["사람문장3"].astype(str)
fin_v["사람문장"]=fin_v["사람문장1"].astype(str)+fin_v["사람문장2"].astype(str)+fin_v["사람문장3"].astype(str)

# training과 validation 합치기
df_concat=pd.concat([fin_t,fin_v])
final_df=df_concat[["사람문장","감정_대분류"]]
final_df=final_df.rename({"감정_대분류":"감정"},axis=1)

#컬럼 내 데이터들의 공백(string) 제거
final_df["감정"]=final_df["감정"].apply(lambda x:x.strip())
final_df["감정"].value_counts()

final_df.head()

                                                사람문장  감정
0  일은 왜 해도 해도 끝이 없을까? 화가 난다.그냥 내가 해결하는 게 나아. 남들한테...  분노
1  이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나....  분노
2  회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...  분노
3  직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...  분노
4  얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.상사인 나에게 먼...  분노

In [39]:
# 감정: 7가지 분류
final_df['감정'].value_counts()

감정
슬픔    20278
불안    10433
분노    10417
당황     9804
행복     7339
Name: count, dtype: int64

## 텍스트 정제

# 챗봇 대화 생성 모델

In [30]:
# 사람문장과 시스템문장 분리하기

# 데이터프레임 섞기 (대화 내용이 이어지기 때문)
shuffled_train = fin_t.sample(frac=1).reset_index(drop=True)
shuffled_test = fin_v.sample(frac=1).reset_index(drop=True)


shuffled_train.head()

# train 데이터
rows = []

# 각 행에 대해 사람문장과 시스템문장을 분리
for idx, row in shuffled_train.iterrows():
    # 사람문장1에 대한 시스템문장1
    if pd.notna(row['사람문장1']) and pd.notna(row['시스템문장1']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장1'],
            '시스템문장': row['시스템문장1']
        })
    
    # 사람문장2에 대한 시스템문장2
    if pd.notna(row['사람문장2']) and pd.notna(row['시스템문장2']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장2'],
            '시스템문장': row['시스템문장2']
        })

    # 사람문장3에 대한 시스템문장3 (NaN이 아닌 경우에만 추가)
    if pd.notna(row['사람문장3']) and pd.notna(row['시스템문장3']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장3'],
            '시스템문장': row['시스템문장3']
        })

# 새로운 데이터 프레임 생성
train = pd.DataFrame(rows)

train.head()

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장,시스템문장
0,청년,여성,대인관계,해당없음,당황,당황,친구가 가지고 싶어 하던 물건을 선물해 주었는데 다른 친구한테 방금 똑같은 걸 받았...,친구가 선물을 주려고 했는데 이미 똑같은 선물을 받은 상태라서 많이 당황하셨을 것 ...
1,청년,여성,대인관계,해당없음,당황,당황,내가 꼭 주고 싶었던 선물인데 이미 받았다니 너무 속상해.,정말 속상하시겠어요. 이 상황을 해결할 방법에는 어떤 것이 있을까요?
2,청년,여성,대인관계,해당없음,당황,당황,친구에게 물어봐서 필요하다면 주고 안 필요하다면 내가 가져야겠어.,운동하고 나 자신을 관리해야겠다고 생각하시는군요.
3,청년,여성,"진로,취업,직장",해당없음,불안,불안,입사 후에 업무에 잘 적응할 수 있을지 정말 불안해.,업무 적응 때문에 불안해하시는군요.
4,청년,여성,"진로,취업,직장",해당없음,불안,불안,내가 다른 사람들보다 꼼꼼해서 느리거든. 결과는 잘 만들 수 있는데 느려서 걱정돼.,그런 상황을 변화시키기 위해서 어떻게 하면 될까요?

In [31]:
train['감정_대분류'].value_counts()

감정_대분류
불안    27960
분노    27480
상처    27429
슬픔    27375
당황    26268
기쁨    18378
Name: count, dtype: int64

In [32]:
# test 데이터
rows = []

# 각 행에 대해 사람문장과 시스템문장을 분리
for idx, row in shuffled_test.iterrows():
    # 사람문장1에 대한 시스템문장1
    if pd.notna(row['사람문장1']) and pd.notna(row['시스템문장1']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장1'],
            '시스템문장': row['시스템문장1']
        })
    
    # 사람문장2에 대한 시스템문장2
    if pd.notna(row['사람문장2']) and pd.notna(row['시스템문장2']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장2'],
            '시스템문장': row['시스템문장2']
        })

    # 사람문장3에 대한 시스템문장3 (NaN이 아닌 경우에만 추가)
    if pd.notna(row['사람문장3']) and pd.notna(row['시스템문장3']):
        rows.append({
            '연령': row['연령'],
            '성별': row['성별'],
            '상황키워드': row['상황키워드'],
            '신체질환': row['신체질환'],
            '감정_대분류': row['감정_대분류'],
            '감정_소분류': row['감정_소분류'],
            '사람문장': row['사람문장3'],
            '시스템문장': row['시스템문장3']
        })

# 새로운 데이터 프레임 생성
test = pd.DataFrame(rows)

test.head()

,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장,시스템문장
0,청년,남성,"연애,결혼,출산",해당없음,불안,초조한,여자친구가 배가 아프다고 해. 그래서 업고 병원을 찾는 중인데 보이질 않아.,여자친구가 아프시다니 정말 초조하겠어요.
1,청년,남성,"연애,결혼,출산",해당없음,불안,초조한,도저히 병원을 못 찾겠는데 어떻게 해야 하지.,병원을 찾고 계시군요. 어떻게 해야 빠르게 찾을 수 있을까요?
2,청년,남성,"연애,결혼,출산",해당없음,불안,초조한,생각해보니 스마트폰으로 병원의 위치를 찾을 수 있어. 빨리 여자친구를 데려가야겠어.,여자친구가 잘 치료받고 아프지 않았으면 좋겠어요.
3,중년,남성,건강,해당없음,당황,부끄러운,시력이 많이 안 좋아져서 검사를 받았는데 스마트폰을 너무 많이 봐서 그렇다고 해. ...,시력 관리를 잘하지 못해 부끄러우시군요. 스마트폰의 사용을 줄이기 위해선 어떤 습관...
4,중년,남성,건강,해당없음,당황,부끄러운,꼭 필요한 순간이 아니면 사용을 안 해야지. 무제한 요금제라서 습관적으로 하게 되는...,데이터를 제한하면 과도한 사용이 줄어들 수도 있겠네요. 스마트폰의 사용을 줄여 눈 ...